#!/usr/bin/env bash
sudo ifconfig lo0 alias 10.254.254.254
docker-sync start && \
docker-compose up -d --build && \
echo "
===================== Done ===================

      Created by Gabriel Matsuoka

      Access your new links:

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== Done ==================="
